### ISSUE TITLE
训练coco2017数据集，训练到40多个epoch时报错这个CUDA error: device-side assert triggered terminate called after throwing an instance of 'c10::Error'

### ISSUE THREAD

**Issue by xlhuang132** [ouening/torchvision-FasterRCNN#3]
`Traceback (most recent call last):
  File "train.py", line 185, in <module>
    main()
  File "train.py", line 166, in main
    train_one_epoch(model, optimizer, data_loader, device, epoch, args.print_freq)
  File "/home/aa/xlhuang/faster_rcnn/Faster-RCNN-with-torchvision/engine.py", line 29, in train_one_epoch
    loss_dict = model(images, targets)
  File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 97, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 365, in forward
    objectness, pred_bbox_deltas, labels, regression_targets)
  File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 296, in compute_loss
    sampled_pos_inds, sampled_neg_inds = self.fg_bg_sampler(labels)
  File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 45, in __call__
    positive = torch.where(matched_idxs_per_image >= 1)[0]
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f10435f22f2 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f10435ef67b in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7f104384a1f9 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f10435da3a4 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6ea43a (0x7f10b740743a in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6ea4e1 (0x7f10b74074e1 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x1ad526 (0x55f5ee2db526 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
frame #7: <unknown function> + 0x10e78c (0x55f5ee23c78c in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
frame #8: <unknown function> + 0xfdb78 (0x55f5ee22bb78 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
frame #9: <unknown function> + 0x10eea7 (0x55f5ee23cea7 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
frame #10: <unknown function> + 0x10eebd (0x55f5ee23cebd in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
frame #11: <unknown function> + 0x10eebd (0x55f5ee23cebd in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
frame #12: PyDict_SetItem + 0x4d2 (0x55f5ee2a4032 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
frame #13: PyDict_SetItemString + 0x4f (0x55f5ee2a4abf in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
frame #14: PyImport_Cleanup + 0x9e (0x55f5ee2dc0ae in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python)
`

`RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
`

**Comment by ouening** [comment]
> `Traceback (most recent call last): File "train.py", line 185, in <module> main() File "train.py", line 166, in main train_one_epoch(model, optimizer, data_loader, device, epoch, args.print_freq) File "/home/aa/xlhuang/faster_rcnn/Faster-RCNN-with-torchvision/engine.py", line 29, in train_one_epoch loss_dict = model(images, targets) File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 705, in forward output = self.module(*inputs[0], **kwargs[0]) File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torchvision/models/detection/generalized_rcnn.py", line 97, in forward proposals, proposal_losses = self.rpn(images, features, targets) File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 365, in forward objectness, pred_bbox_deltas, labels, regression_targets) File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torchvision/models/detection/rpn.py", line 296, in compute_loss sampled_pos_inds, sampled_neg_inds = self.fg_bg_sampler(labels) File "/home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torchvision/models/detection/_utils.py", line 45, in __call__ positive = torch.where(matched_idxs_per_image >= 1)[0] RuntimeError: CUDA error: device-side assert triggered terminate called after throwing an instance of 'c10::Error' what(): CUDA error: device-side assert triggered Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first): frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f10435f22f2 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libc10.so) frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f10435ef67b in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libc10.so) frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7f104384a1f9 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libc10_cuda.so) frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f10435da3a4 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libc10.so) frame #4: <unknown function> + 0x6ea43a (0x7f10b740743a in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libtorch_python.so) frame #5: <unknown function> + 0x6ea4e1 (0x7f10b74074e1 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/lib/python3.7/site-packages/torch/lib/libtorch_python.so) frame #6: <unknown function> + 0x1ad526 (0x55f5ee2db526 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) frame #7: <unknown function> + 0x10e78c (0x55f5ee23c78c in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) frame #8: <unknown function> + 0xfdb78 (0x55f5ee22bb78 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) frame #9: <unknown function> + 0x10eea7 (0x55f5ee23cea7 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) frame #10: <unknown function> + 0x10eebd (0x55f5ee23cebd in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) frame #11: <unknown function> + 0x10eebd (0x55f5ee23cebd in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) frame #12: PyDict_SetItem + 0x4d2 (0x55f5ee2a4032 in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) frame #13: PyDict_SetItemString + 0x4f (0x55f5ee2a4abf in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) frame #14: PyImport_Cleanup + 0x9e (0x55f5ee2dc0ae in /home/aa/xlhuang/anaconda3/envs/faster_rcnn/bin/python) `
> 
> `RuntimeError: CUDA error: device-side assert triggered terminate called after throwing an instance of 'c10::Error' what(): CUDA error: device-side assert triggered `

检查一下类别数量那些对吗

**Comment by xlhuang132** [comment]
我就是直接用coco数据集训练的，这个问题已经解决
```
class BalancedPositiveNegativeSampler(object):
	...
 def __call__(self, matched_idxs):
 		...	
        for matched_idxs_per_image in matched_idxs:
        	...
            ### 这里报错！！！
            positive = torch.nonzero(matched_idxs_per_image >= 1).squeeze(1)
            negative = torch.nonzero(matched_idxs_per_image == 0).squeeze(1)
 
            ...
 
            # randomly select positive and negative examples
            # 将下面2句注释掉，然后改成后面4句，就能运行辣    
            # perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
            # perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]
            
            perm1 = torch.randperm(positive.numel())[:num_pos]
            perm2 = torch.randperm(negative.numel())[:num_neg] ################# the elments inside the perm2 are too large
            perm1.cuda()
            perm2.cuda()
```

按照上面改一下就行了，不知道为啥会出现这个问题
